### ISSUE TITLE
lazysodium crashes with latest JNA (5.1.0)

### ISSUE THREAD

**Issue by adityapk00** [terl/lazysodium-android#15] opened 2018-11-18 21:59 UTC
Quickstart recommends using the latest JNA version (5.1.0), but `new LazySodiumAndroid(new SodiumAndroid())` crashes on startup with:
`java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-x86/libjnidispatch.so) not found in resource path (.)`

The internets are also unhelpful with this error message. Changing the JNA dependency to `4.5.1` works.

**Comment by gurpreet-** [comment] 2018-11-18 22:56
Hi thanks for reporting this.

I'm currently working on a fix for this. Up until then use 4.5.1

**Comment by gurpreet-** [comment] 2019-03-07 00:01
JNA with version `5.2.0` works correctly and as intended.

**Closed by gurpreet-** 2019-03-07 00:01 UTC
Labels: bug, resolved

**Comment by malenalbc** [comment] 2020-01-13 13:26
This is happening to me with version `5.5.0@aar` and version `4.1.0@aar` of the library:
```
  implementation "com.goterl.lazycode:lazysodium-android:4.1.0@aar"
    implementation 'net.java.dev.jna:jna:5.5.0@aar'
```

The stacktrace when building:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/darwin/libjnidispatch.jnilib) not found in resource path ([file:/Users/username/Library/Android/sdk/platforms/android-29/android.jar, file:/Users/username/Library/Android/sdk/platforms/android-29/data/res/, file:/Users/username/Documents/RepoOut/AndroidLib/androidtezos/build/intermediates/javac/debug/classes/, file:/Users/username/Documents/RepoOut/AndroidLib/androidtezos/build/tmp/kotlin-classes/debug/, file:/Users/username/Documents/RepoOut/AndroidLib/androidtezos/build/generated/res/resValues/debug/, file:/Users/username/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-android-extensions-runtime/1.3.61/289bdf25b4886749e040c7a7d3aab8a57f85c631/kotlin-android-extensions-runtime-1.3.61.jar, file:/Users/username/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.61/70dffc5f8ac5ea7c34f30deac5b9d8b1d48af066/kotlin-stdlib-jdk7-1.3.61.jar, file:/Users/username/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.61/4702105e97f7396ae41b113fdbdc180ec1eb1e36/kotlin-stdlib-1.3.61.jar, file:/Users/username/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.61/65abb71d5afb850b68be03987b08e2c864ca3110/kotlin-stdlib-common-1.3.61.jar, file:/Users/username/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar, file:/Users/username/.gradle/caches/transforms-2/files-2.1/f5502816b14bb62549b26ad4e2f02a4d/lazysodium-android-4.1.0/jars/classes.jar, file:/Users/username/.gradle/caches/transforms-2/files-2.1/a0c6aecc41384ff6be5d4099b29da256/jna-5.5.0/jars/classes.jar, file:/Users/username/.gradle/caches/transforms-2/files-2.1/a0c6aecc41384ff6be5d4099b29da256/jna-5.5.0/res/, file:/Applications/Android%20Studio.app/Contents/lib/idea_rt.jar])
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1032)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.goterl.lazycode.lazysodium.SodiumAndroid.<init>(SodiumAndroid.java:37)
	at com.goterl.lazycode.lazysodium.SodiumAndroid.<init>(SodiumAndroid.java:17)
```

**Comment by acugniere** [comment] 2021-02-04 16:50
Still have this issue with `4.3.2` and jna `5.5.0`

**Comment by gurpreet-** [comment] 2021-02-08 22:48
Please upgrade to the latest version of the library ASAP @malenalbc. That should fix it.

**Comment by AndroidDeveloperLB** [comment] 2021-04-05 06:20
For me this worked fine:
```
    implementation "com.goterl:lazysodium-android:5.0.0@aar"
    implementation 'net.java.dev.jna:jna:5.8.0@aar'
```

I suggest trying it out.
